// Generated by scripts/bundle-migrations.ts from migrations/. Don't edit: run `pnpm --filter @send0/db generate`.
import type { BundledMigration } from "./migrate-bundled";

/** Every migration in the journal, oldest first, with its SQL inlined. */
export const MIGRATIONS: BundledMigration[] = [
  {
    "tag": "0000_init",
    "folderMillis": 1791200978199,
    "hash": "5b41b5b825678c305dba30c858d621871f9835d65bc963a822e0cd042e56c3a2",
    "statements": [
      "CREATE TABLE \"api_keys\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"prefix\" text NOT NULL,\n\t\"hash\" text NOT NULL,\n\t\"mode\" text NOT NULL,\n\t\"scopes\" text[] NOT NULL,\n\t\"inbox_ids\" text[],\n\t\"last_used_at\" timestamp with time zone,\n\t\"revoked_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"attachments\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"message_id\" text NOT NULL,\n\t\"filename\" text,\n\t\"content_type\" text NOT NULL,\n\t\"size\" integer NOT NULL,\n\t\"content_id\" text,\n\t\"inline\" boolean DEFAULT false NOT NULL,\n\t\"blob_key\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"deliveries\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"webhook_id\" text NOT NULL,\n\t\"event_id\" text NOT NULL,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"last_status_code\" integer,\n\t\"last_error\" text,\n\t\"last_duration_ms\" integer,\n\t\"next_attempt_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"domains\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text,\n\t\"name\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"dkim_selector\" text,\n\t\"records\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"verified_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"drafts\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"inbox_id\" text NOT NULL,\n\t\"thread_id\" text,\n\t\"payload\" jsonb NOT NULL,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"decided_by\" text,\n\t\"decided_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"events\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"inbox_id\" text,\n\t\"type\" text NOT NULL,\n\t\"payload\" jsonb NOT NULL,\n\t\"dispatched_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"idempotency_keys\" (\n\t\"org_id\" text NOT NULL,\n\t\"key\" text NOT NULL,\n\t\"route\" text NOT NULL,\n\t\"request_hash\" text NOT NULL,\n\t\"response_status\" integer,\n\t\"response_body\" jsonb,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"idempotency_keys_org_id_key_pk\" PRIMARY KEY(\"org_id\",\"key\")\n);\n",
      "\nCREATE TABLE \"inboxes\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"domain_id\" text NOT NULL,\n\t\"local_part\" text NOT NULL,\n\t\"display_name\" text,\n\t\"mode\" text DEFAULT 'live' NOT NULL,\n\t\"send_policy\" text DEFAULT 'reply_only' NOT NULL,\n\t\"status\" text DEFAULT 'active' NOT NULL,\n\t\"retention_days\" integer DEFAULT 7 NOT NULL,\n\t\"metadata\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"expires_at\" timestamp with time zone,\n\t\"deleted_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"messages\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"inbox_id\" text NOT NULL,\n\t\"thread_id\" text NOT NULL,\n\t\"direction\" text NOT NULL,\n\t\"status\" text NOT NULL,\n\t\"rfc_message_id\" text,\n\t\"in_reply_to\" text[] DEFAULT '{}'::text[] NOT NULL,\n\t\"references\" text[] DEFAULT '{}'::text[] NOT NULL,\n\t\"from\" jsonb,\n\t\"to\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"cc\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"reply_to\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"subject\" text DEFAULT '' NOT NULL,\n\t\"text\" text,\n\t\"html\" text,\n\t\"extracted_text\" text,\n\t\"extracted\" jsonb,\n\t\"auth\" jsonb,\n\t\"safety\" jsonb,\n\t\"tag\" text,\n\t\"size\" integer DEFAULT 0 NOT NULL,\n\t\"raw_key\" text,\n\t\"provider_message_id\" text,\n\t\"error\" text,\n\t\"sent_at\" timestamp with time zone,\n\t\"received_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"tsv\" \"tsvector\" GENERATED ALWAYS AS (setweight(to_tsvector('simple', coalesce(\"messages\".\"subject\", '')), 'A') || setweight(to_tsvector('simple', coalesce(\"messages\".\"extracted_text\", \"messages\".\"text\", '')), 'B')) STORED\n);\n",
      "\nCREATE TABLE \"orgs\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"plan\" text DEFAULT 'free' NOT NULL,\n\t\"status\" text DEFAULT 'active' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"suppressions\" (\n\t\"org_id\" text NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"reason\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"suppressions_org_id_email_pk\" PRIMARY KEY(\"org_id\",\"email\")\n);\n",
      "\nCREATE TABLE \"threads\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"inbox_id\" text NOT NULL,\n\t\"subject\" text DEFAULT '' NOT NULL,\n\t\"subject_norm\" text DEFAULT '' NOT NULL,\n\t\"participants\" text[] DEFAULT '{}'::text[] NOT NULL,\n\t\"message_count\" integer DEFAULT 0 NOT NULL,\n\t\"last_message_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"labels\" text[] DEFAULT '{}'::text[] NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"usage\" (\n\t\"org_id\" text NOT NULL,\n\t\"period\" text NOT NULL,\n\t\"sent\" integer DEFAULT 0 NOT NULL,\n\t\"received\" integer DEFAULT 0 NOT NULL,\n\t\"storage_bytes\" bigint DEFAULT 0 NOT NULL,\n\tCONSTRAINT \"usage_org_id_period_pk\" PRIMARY KEY(\"org_id\",\"period\")\n);\n",
      "\nCREATE TABLE \"webhooks\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"url\" text NOT NULL,\n\t\"secret\" text NOT NULL,\n\t\"events\" text[] NOT NULL,\n\t\"inbox_ids\" text[],\n\t\"status\" text DEFAULT 'enabled' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nALTER TABLE \"api_keys\" ADD CONSTRAINT \"api_keys_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"attachments\" ADD CONSTRAINT \"attachments_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"attachments\" ADD CONSTRAINT \"attachments_message_id_messages_id_fk\" FOREIGN KEY (\"message_id\") REFERENCES \"public\".\"messages\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"deliveries\" ADD CONSTRAINT \"deliveries_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"deliveries\" ADD CONSTRAINT \"deliveries_webhook_id_webhooks_id_fk\" FOREIGN KEY (\"webhook_id\") REFERENCES \"public\".\"webhooks\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"deliveries\" ADD CONSTRAINT \"deliveries_event_id_events_id_fk\" FOREIGN KEY (\"event_id\") REFERENCES \"public\".\"events\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"domains\" ADD CONSTRAINT \"domains_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"drafts\" ADD CONSTRAINT \"drafts_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"drafts\" ADD CONSTRAINT \"drafts_inbox_id_inboxes_id_fk\" FOREIGN KEY (\"inbox_id\") REFERENCES \"public\".\"inboxes\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"drafts\" ADD CONSTRAINT \"drafts_thread_id_threads_id_fk\" FOREIGN KEY (\"thread_id\") REFERENCES \"public\".\"threads\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"events\" ADD CONSTRAINT \"events_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"idempotency_keys\" ADD CONSTRAINT \"idempotency_keys_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"inboxes\" ADD CONSTRAINT \"inboxes_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"inboxes\" ADD CONSTRAINT \"inboxes_domain_id_domains_id_fk\" FOREIGN KEY (\"domain_id\") REFERENCES \"public\".\"domains\"(\"id\") ON DELETE no action ON UPDATE no action;",
      "\nALTER TABLE \"messages\" ADD CONSTRAINT \"messages_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"messages\" ADD CONSTRAINT \"messages_inbox_id_inboxes_id_fk\" FOREIGN KEY (\"inbox_id\") REFERENCES \"public\".\"inboxes\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"messages\" ADD CONSTRAINT \"messages_thread_id_threads_id_fk\" FOREIGN KEY (\"thread_id\") REFERENCES \"public\".\"threads\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"suppressions\" ADD CONSTRAINT \"suppressions_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"threads\" ADD CONSTRAINT \"threads_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"threads\" ADD CONSTRAINT \"threads_inbox_id_inboxes_id_fk\" FOREIGN KEY (\"inbox_id\") REFERENCES \"public\".\"inboxes\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"usage\" ADD CONSTRAINT \"usage_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"webhooks\" ADD CONSTRAINT \"webhooks_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nCREATE UNIQUE INDEX \"api_keys_hash_idx\" ON \"api_keys\" USING btree (\"hash\");",
      "\nCREATE INDEX \"api_keys_org_idx\" ON \"api_keys\" USING btree (\"org_id\");",
      "\nCREATE INDEX \"attachments_message_idx\" ON \"attachments\" USING btree (\"message_id\");",
      "\nCREATE UNIQUE INDEX \"deliveries_webhook_event_idx\" ON \"deliveries\" USING btree (\"webhook_id\",\"event_id\");",
      "\nCREATE INDEX \"deliveries_due_idx\" ON \"deliveries\" USING btree (\"next_attempt_at\") WHERE \"deliveries\".\"status\" = 'pending';",
      "\nCREATE UNIQUE INDEX \"domains_name_idx\" ON \"domains\" USING btree (lower(\"name\"));",
      "\nCREATE INDEX \"domains_org_idx\" ON \"domains\" USING btree (\"org_id\");",
      "\nCREATE INDEX \"drafts_inbox_idx\" ON \"drafts\" USING btree (\"inbox_id\",\"created_at\" DESC NULLS LAST);",
      "\nCREATE INDEX \"events_org_recent_idx\" ON \"events\" USING btree (\"org_id\",\"created_at\" DESC NULLS LAST);",
      "\nCREATE INDEX \"events_undispatched_idx\" ON \"events\" USING btree (\"created_at\") WHERE \"events\".\"dispatched_at\" is null;",
      "\nCREATE INDEX \"idempotency_created_idx\" ON \"idempotency_keys\" USING btree (\"created_at\");",
      "\nCREATE UNIQUE INDEX \"inboxes_address_idx\" ON \"inboxes\" USING btree (\"domain_id\",lower(\"local_part\"));",
      "\nCREATE INDEX \"inboxes_org_idx\" ON \"inboxes\" USING btree (\"org_id\",\"created_at\" DESC NULLS LAST);",
      "\nCREATE INDEX \"messages_inbox_recent_idx\" ON \"messages\" USING btree (\"inbox_id\",\"created_at\" DESC NULLS LAST);",
      "\nCREATE INDEX \"messages_thread_idx\" ON \"messages\" USING btree (\"thread_id\",\"created_at\");",
      "\nCREATE INDEX \"messages_rfc_id_idx\" ON \"messages\" USING btree (\"inbox_id\",\"rfc_message_id\");",
      "\nCREATE UNIQUE INDEX \"messages_inbound_dedupe_idx\" ON \"messages\" USING btree (\"inbox_id\",\"rfc_message_id\") WHERE \"messages\".\"direction\" = 'in' and \"messages\".\"rfc_message_id\" is not null;",
      "\nCREATE INDEX \"messages_tsv_idx\" ON \"messages\" USING gin (\"tsv\");",
      "\nCREATE INDEX \"threads_inbox_recent_idx\" ON \"threads\" USING btree (\"inbox_id\",\"last_message_at\" DESC NULLS LAST);",
      "\nCREATE INDEX \"threads_inbox_subject_idx\" ON \"threads\" USING btree (\"inbox_id\",\"subject_norm\",\"last_message_at\" DESC NULLS LAST);",
      "\nCREATE INDEX \"webhooks_org_idx\" ON \"webhooks\" USING btree (\"org_id\");"
    ]
  },
  {
    "tag": "0001_sending_controls",
    "folderMillis": 1791272607799,
    "hash": "f6f1ba5217b86a4dee6d7c58884f663a090aaa27b039fca88949eabc0ea73dbe",
    "statements": [
      "ALTER TABLE \"orgs\" ADD COLUMN \"daily_send_limit\" integer DEFAULT 50 NOT NULL;",
      "\nALTER TABLE \"orgs\" ADD COLUMN \"sending_paused_at\" timestamp with time zone;",
      "\nALTER TABLE \"orgs\" ADD COLUMN \"sending_paused_reason\" text;"
    ]
  },
  {
    "tag": "0002_dashboard_auth",
    "folderMillis": 1791286811188,
    "hash": "f8de843039cb8ba27255ef0788ecc437b40044796ce760e740368b9ebb830db7",
    "statements": [
      "CREATE TABLE \"auth_tokens\" (\n\t\"token_hash\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"purpose\" text NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"used_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"members\" (\n\t\"org_id\" text NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"role\" text DEFAULT 'owner' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"members_org_id_user_id_pk\" PRIMARY KEY(\"org_id\",\"user_id\")\n);\n",
      "\nCREATE TABLE \"rate_limits\" (\n\t\"key\" text PRIMARY KEY NOT NULL,\n\t\"count\" integer DEFAULT 0 NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL\n);\n",
      "\nCREATE TABLE \"sessions\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"user_id\" text NOT NULL,\n\t\"token_hash\" text NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"last_seen_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"ip\" text,\n\t\"user_agent\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"users\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"name\" text,\n\t\"password_hash\" text NOT NULL,\n\t\"email_verified_at\" timestamp with time zone,\n\t\"onboarded_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nALTER TABLE \"auth_tokens\" ADD CONSTRAINT \"auth_tokens_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"members\" ADD CONSTRAINT \"members_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"members\" ADD CONSTRAINT \"members_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nCREATE INDEX \"auth_tokens_user_idx\" ON \"auth_tokens\" USING btree (\"user_id\",\"purpose\");",
      "\nCREATE INDEX \"members_user_idx\" ON \"members\" USING btree (\"user_id\");",
      "\nCREATE INDEX \"rate_limits_expires_idx\" ON \"rate_limits\" USING btree (\"expires_at\");",
      "\nCREATE UNIQUE INDEX \"sessions_token_idx\" ON \"sessions\" USING btree (\"token_hash\");",
      "\nCREATE INDEX \"sessions_user_idx\" ON \"sessions\" USING btree (\"user_id\");",
      "\nCREATE UNIQUE INDEX \"users_email_idx\" ON \"users\" USING btree (lower(\"email\"));"
    ]
  },
  {
    "tag": "0003_teams",
    "folderMillis": 1791294983715,
    "hash": "79d0db46f9299f3547f1843adbfd6db73c0f2aafca1d806877eb76960b95204d",
    "statements": [
      "CREATE TABLE \"invites\" (\n\t\"id\" text PRIMARY KEY NOT NULL,\n\t\"org_id\" text NOT NULL,\n\t\"email\" text NOT NULL,\n\t\"role\" text NOT NULL,\n\t\"token_hash\" text NOT NULL,\n\t\"invited_by\" text,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"accepted_at\" timestamp with time zone,\n\t\"revoked_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nALTER TABLE \"orgs\" ADD COLUMN \"deleted_at\" timestamp with time zone;",
      "\nALTER TABLE \"sessions\" ADD COLUMN \"org_id\" text;",
      "\nALTER TABLE \"invites\" ADD CONSTRAINT \"invites_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"invites\" ADD CONSTRAINT \"invites_invited_by_users_id_fk\" FOREIGN KEY (\"invited_by\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nCREATE UNIQUE INDEX \"invites_token_idx\" ON \"invites\" USING btree (\"token_hash\");",
      "\nCREATE UNIQUE INDEX \"invites_open_idx\" ON \"invites\" USING btree (\"org_id\",lower(\"email\")) WHERE \"invites\".\"accepted_at\" is null and \"invites\".\"revoked_at\" is null;",
      "\nALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_org_id_orgs_id_fk\" FOREIGN KEY (\"org_id\") REFERENCES \"public\".\"orgs\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nCREATE UNIQUE INDEX \"members_one_owner_idx\" ON \"members\" USING btree (\"org_id\") WHERE \"members\".\"role\" = 'owner';"
    ]
  }
];
