import type { BlobStore } from "@send0/adapters/blob";
import { newId, resolveThread, type ParsedMessage } from "@send0/core";
import { schema, type Db } from "@send0/db";
import { and, desc, eq, gte, inArray, sql } from "drizzle-orm";
import type { InboxRecord } from "./inbox-lookup";
import { toEnvelope, type EventEnvelope } from "./events";
import { serializeMessage } from "./serialize";

const { threads, messages, attachments, events, usage } = schema;

export interface IngestInput {
  inbox: InboxRecord;
  /** Generated by the caller, so the raw .eml can be stored under the same id first */
  messageId: string;
  rawKey: string;
  parsed: ParsedMessage;
  tag: string | null;
  receivedAt: Date;
}

export type IngestResult =
  | { duplicate: true; messageId: string }
  | {
      duplicate: false;
      messageId: string;
      threadId: string;
      threadMatchedBy: "in-reply-to" | "references" | "subject" | null;
      event: { id: string; type: "message.received"; orgId: string; inboxId: string; payload: Record<string, unknown> };
      envelope: EventEnvelope;
    };

class Duplicate extends Error {}

/** A Postgres text[] literal. Drizzle would otherwise expand a JS array into a comma list. */
const textArray = (values: string[]) =>
  values.length
    ? sql`ARRAY[${sql.join(
        values.map((v) => sql`${v}`),
        sql`, `,
      )}]::text[]`
    : sql`'{}'::text[]`;

export const attachmentKey = (orgId: string, messageId: string, attachmentId: string) => `att/${orgId}/${messageId}/${attachmentId}`;

function participantsOf(p: ParsedMessage, inboxAddress: string): string[] {
  const all = [p.from, ...p.to, ...p.cc, ...p.replyTo].filter(Boolean).map((m) => m!.email.toLowerCase());
  return [...new Set(all)].filter((e) => e !== inboxAddress.toLowerCase());
}

/**
 * Stores a parsed inbound message: attachments to blob storage, then thread + message +
 * attachment rows + a message.received outbox event in one transaction.
 * Safe to call twice for the same message (sender retries): the second call is a no-op.
 */
export async function ingestMessage(db: Db, blobs: BlobStore, input: IngestInput): Promise<IngestResult> {
  const { inbox, parsed, messageId } = input;

  if (parsed.rfcMessageId) {
    const [existing] = await db
      .select({ id: messages.id })
      .from(messages)
      .where(and(eq(messages.inboxId, inbox.id), eq(messages.rfcMessageId, parsed.rfcMessageId), eq(messages.direction, "in")));
    if (existing) return { duplicate: true, messageId: existing.id };
  }

  // Attachments go to storage before the transaction; rows reference them inside it.
  const stored = await Promise.all(
    parsed.attachments.map(async (a) => {
      const id = newId("att");
      const key = attachmentKey(inbox.orgId, messageId, id);
      await blobs.put(key, a.content as Uint8Array<ArrayBuffer>, {
        contentType: a.contentType || "application/octet-stream",
        metadata: { message_id: messageId },
      });
      return { a, id, key };
    }),
  );

  const participants = participantsOf(parsed, inbox.address);

  try {
    return await db.transaction(async (tx) => {
      const match = await resolveThread(
        {
          inReplyTo: parsed.inReplyTo,
          references: parsed.references,
          subjectNorm: parsed.subjectNorm,
          participants,
          date: input.receivedAt,
        },
        {
          findByMessageIds: async (ids) => {
            const [row] = await tx
              .select({ threadId: messages.threadId })
              .from(messages)
              .where(and(eq(messages.inboxId, inbox.id), inArray(messages.rfcMessageId, ids)))
              .orderBy(desc(messages.createdAt))
              .limit(1);
            return row?.threadId ?? null;
          },
          findBySubject: (subjectNorm, since) =>
            tx
              .select({ threadId: threads.id, participants: threads.participants, lastMessageAt: threads.lastMessageAt })
              .from(threads)
              .where(and(eq(threads.inboxId, inbox.id), eq(threads.subjectNorm, subjectNorm), gte(threads.lastMessageAt, since)))
              .orderBy(desc(threads.lastMessageAt))
              .limit(10),
        },
      );

      let threadId = match.threadId;
      if (!threadId) {
        threadId = newId("thr");
        await tx.insert(threads).values({
          id: threadId,
          orgId: inbox.orgId,
          inboxId: inbox.id,
          subject: parsed.subject,
          subjectNorm: parsed.subjectNorm,
          participants,
          lastMessageAt: input.receivedAt,
          createdAt: input.receivedAt,
        });
      }

      const [message] = await tx
        .insert(messages)
        .values({
          id: messageId,
          orgId: inbox.orgId,
          inboxId: inbox.id,
          threadId,
          direction: "in",
          status: "received",
          rfcMessageId: parsed.rfcMessageId,
          inReplyTo: parsed.inReplyTo,
          references: parsed.references,
          from: parsed.from,
          to: parsed.to,
          cc: parsed.cc,
          replyTo: parsed.replyTo,
          subject: parsed.subject,
          text: parsed.text,
          html: parsed.html,
          extractedText: parsed.extractedText,
          extracted: parsed.extracted,
          auth: parsed.auth,
          safety: parsed.safety,
          tag: input.tag,
          size: parsed.size,
          rawKey: input.rawKey,
          receivedAt: input.receivedAt,
          createdAt: input.receivedAt,
        })
        .onConflictDoNothing()
        .returning();
      if (!message) throw new Duplicate();

      await tx
        .update(threads)
        .set({
          messageCount: sql`${threads.messageCount} + 1`,
          lastMessageAt: sql`greatest(${threads.lastMessageAt}, ${input.receivedAt.toISOString()}::timestamptz)`,
          participants: sql`(select coalesce(array_agg(distinct p), '{}') from unnest(${threads.participants} || ${textArray(participants)}) as p)`,
        })
        .where(eq(threads.id, threadId));

      const attRows = stored.length
        ? await tx
            .insert(attachments)
            .values(
              stored.map(({ a, id, key }) => ({
                id,
                orgId: inbox.orgId,
                messageId,
                filename: a.filename,
                contentType: a.contentType || "application/octet-stream",
                size: a.size,
                contentId: a.contentId,
                inline: a.inline,
                blobKey: key,
              })),
            )
            .returning()
        : [];

      const event = {
        id: newId("evt"),
        type: "message.received" as const,
        orgId: inbox.orgId,
        inboxId: inbox.id,
        payload: { data: serializeMessage(message, attRows) } as Record<string, unknown>,
      };
      await tx.insert(events).values({ ...event, createdAt: input.receivedAt });
      const envelope = toEnvelope({ ...event, createdAt: input.receivedAt });

      const period = input.receivedAt.toISOString().slice(0, 7);
      await tx
        .insert(usage)
        .values({ orgId: inbox.orgId, period, received: 1 })
        .onConflictDoUpdate({ target: [usage.orgId, usage.period], set: { received: sql`${usage.received} + 1` } });

      return { duplicate: false as const, messageId, threadId, threadMatchedBy: match.matchedBy, event, envelope };
    });
  } catch (err) {
    // Lost a race with a concurrent delivery of the same message.
    if (err instanceof Duplicate) return { duplicate: true, messageId };
    throw err;
  }
}
