/**
 * Writes src/migrations.generated.ts: every SQL migration, inlined, for runtimes that can't read the
 * migrations folder (Workers). Runs after `drizzle-kit generate`; a test fails when the file is stale.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/** The package's migrations folder and the generated module's path. */
export const MIGRATIONS_DIR = fileURLToPath(new URL("../migrations", import.meta.url).href);
export const GENERATED_FILE = fileURLToPath(new URL("../src/migrations.generated.ts", import.meta.url).href);

interface Journal {
  entries: { tag: string; when: number }[];
}

/**
 * The generated module's source. Each migration is computed exactly as drizzle's `readMigrationFiles`
 * does: statements split on the breakpoint marker, `hash` = sha256 of the file, `folderMillis` = the journal's `when`.
 */
export function renderMigrationsModule(folder: string = MIGRATIONS_DIR): string {
  const journal = JSON.parse(readFileSync(path.join(folder, "meta", "_journal.json"), "utf8")) as Journal;
  const migrations = journal.entries.map((e) => {
    const query = readFileSync(path.join(folder, `${e.tag}.sql`)).toString();
    return {
      tag: e.tag,
      folderMillis: e.when,
      hash: createHash("sha256").update(query).digest("hex"),
      statements: query.split("--> statement-breakpoint"),
    };
  });
  return [
    "// Generated by scripts/bundle-migrations.ts from migrations/. Don't edit: run `pnpm --filter @send0/db generate`.",
    'import type { BundledMigration } from "./migrate-bundled";',
    "",
    "/** Every migration in the journal, oldest first, with its SQL inlined. */",
    `export const MIGRATIONS: BundledMigration[] = ${JSON.stringify(migrations, null, 2)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(GENERATED_FILE, renderMigrationsModule());
  console.log(`wrote ${GENERATED_FILE}`);
}
