# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from typing import Annotated, Any, Literal


class Mailbox(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str | None
    email: str


class Error1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: str
    """
    Stable, machine-readable code, e.g. not_found, recipient_not_allowed
    """
    message: str
    param: str | None = None
    """
    The request field the error is about
    """
    request_id: str | None = None


class Error(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    error: Error1


class Attachment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    filename: str | None
    content_type: str
    size: int
    inline: bool
    content_id: str | None


class AttachmentDownload(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    filename: str | None
    content_type: str
    size: int
    inline: bool
    content_id: str | None
    object: Literal['attachment']
    message_id: str
    download_url: str
    """
    Pre-signed URL, valid until expires_at
    """
    expires_at: AwareDatetime


class Extracted(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    otp: str | None
    """
    Most likely one-time code
    """
    links: list[str]
    action_link: str | None
    """
    Most likely verify / sign-in / reset link
    """


class Auth(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    spf: str
    dkim: str
    dmarc: str


class Safety(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    prompt_injection: Literal['none', 'suspected', 'likely']
    reasons: list[str]


class Message(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['message']
    id: str
    inbox_id: str
    thread_id: str
    direction: Literal['in', 'out']
    status: Literal[
        'received', 'queued', 'sent', 'delivered', 'bounced', 'complained', 'failed'
    ]
    rfc_message_id: str | None
    in_reply_to: list[str]
    references: list[str]
    from_: Annotated[Mailbox | None, Field(alias='from')]
    to: list[Mailbox]
    cc: list[Mailbox]
    reply_to: list[Mailbox]
    subject: str
    text: str | None
    html: str | None = None
    """
    Only on single-message reads and threads with include_html=true
    """
    extracted_text: str | None
    """
    New text only: quoted history, forwards and signatures removed
    """
    extracted: Extracted | None
    auth: Auth | None
    safety: Safety | None
    tag: str | None
    """
    Plus-address tag, e.g. task42 for bot+task42@
    """
    attachments: list[Attachment]
    size: int
    sent_at: AwareDatetime | None
    received_at: AwareDatetime | None
    created_at: AwareDatetime


class LatestMessage(BaseModel):
    """
    The newest message, for list previews
    """

    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    direction: Literal['in', 'out']
    from_: Annotated[Mailbox | None, Field(alias='from')]
    snippet: str
    """
    Start of the new text (quotes and signatures removed), whitespace collapsed
    """


class Thread(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['thread']
    id: str
    inbox_id: str
    subject: str
    participants: list[str]
    message_count: int
    labels: list[str]
    latest_message: LatestMessage | None
    """
    The newest message, for list previews
    """
    last_message_at: AwareDatetime
    created_at: AwareDatetime


class ThreadWithMessages(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['thread']
    id: str
    inbox_id: str
    subject: str
    participants: list[str]
    message_count: int
    labels: list[str]
    latest_message: LatestMessage | None
    """
    The newest message, for list previews
    """
    last_message_at: AwareDatetime
    created_at: AwareDatetime
    messages: list[Message]


class Inbox(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['inbox']
    id: str
    address: str
    local_part: str
    domain: str
    display_name: str | None
    mode: Literal['live', 'sandbox']
    send_policy: Literal['open', 'reply_only', 'approval']
    status: Literal['active', 'suspended', 'deleted']
    retention_days: int
    metadata: dict[str, str | float | bool | None]
    expires_at: AwareDatetime | None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class DeletedInbox(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['inbox']
    id: str
    address: str
    local_part: str
    domain: str
    display_name: str | None
    mode: Literal['live', 'sandbox']
    send_policy: Literal['open', 'reply_only', 'approval']
    status: Literal['active', 'suspended', 'deleted']
    retention_days: int
    metadata: dict[str, str | float | bool | None]
    expires_at: AwareDatetime | None
    created_at: AwareDatetime
    updated_at: AwareDatetime
    deleted: Literal[True]


class ApiKey(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['api_key']
    id: str
    name: str
    prefix: str
    mode: Literal['live', 'test']
    scopes: list[str]
    inbox_ids: list[str] | None
    last_used_at: AwareDatetime | None
    created_at: AwareDatetime


class ApiKeyWithSecret(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['api_key']
    id: str
    name: str
    prefix: str
    mode: Literal['live', 'test']
    scopes: list[str]
    inbox_ids: list[str] | None
    last_used_at: AwareDatetime | None
    created_at: AwareDatetime
    key: str
    """
    Shown once
    """


class RevokedApiKey(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['api_key']
    id: str
    name: str
    prefix: str
    mode: Literal['live', 'test']
    scopes: list[str]
    inbox_ids: list[str] | None
    last_used_at: AwareDatetime | None
    created_at: AwareDatetime
    revoked: Literal[True]


class Webhook(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['webhook']
    id: str
    url: str
    events: list[str]
    inbox_ids: list[str] | None
    status: Literal['enabled', 'disabled']
    created_at: AwareDatetime


class WebhookWithSecret(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['webhook']
    id: str
    url: str
    events: list[str]
    inbox_ids: list[str] | None
    status: Literal['enabled', 'disabled']
    created_at: AwareDatetime
    secret: str
    """
    Signing secret, shown once
    """


class DeletedWebhook(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['webhook']
    id: str
    url: str
    events: list[str]
    inbox_ids: list[str] | None
    status: Literal['enabled', 'disabled']
    created_at: AwareDatetime
    deleted: Literal[True]


class WebhookTestResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['event']
    id: str
    type: Literal['webhook.test']
    delivery_id: str


class Delivery(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['delivery']
    id: str
    webhook_id: str
    event_id: str
    event_type: str | None
    status: Literal['pending', 'succeeded', 'failed']
    attempts: int
    last_status_code: int | None
    last_error: str | None
    last_duration_ms: int | None
    next_attempt_at: AwareDatetime | None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class Draft(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['draft']
    id: str
    inbox_id: str
    thread_id: str | None
    status: Literal['pending', 'approved', 'rejected', 'sent']
    kind: Literal['new', 'reply', 'forward']
    to: list[Mailbox]
    cc: list[Mailbox]
    bcc: list[Mailbox]
    subject: str
    text: str | None
    html: str | None
    decided_by: str | None
    decided_at: AwareDatetime | None
    created_at: AwareDatetime


class WaitResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['wait_result']
    timed_out: bool
    message: Message | None
    """
    The first matching message, or null on timeout
    """


class Event(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    object: Literal['event']
    type: str
    """
    message.received, message.sent, message.delivered, message.bounced, message.complained, draft.created, inbox.suspended, webhook.test
    """
    created_at: AwareDatetime
    inbox_id: str | None
    data: dict[str, Any]
    """
    The payload. message.*: the message (without html). inbox.suspended: { scope: "org" | "inbox", reason, … }; "org" means sending is paused account-wide, "inbox" that one inbox is suspended.
    """


class Inboxes(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    used: int
    limit: int | None
    """
    null when the install has no inbox cap (self-hosted)
    """


class SendsToday(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    used: int
    limit: int | None
    """
    null when the install has no daily cap (self-hosted)
    """
    resets_at: AwareDatetime
    """
    Midnight UTC, when the daily count starts over
    """


class Sending(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    paused: bool
    reason: str | None
    paused_at: AwareDatetime | None


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['usage']
    plan: Literal['free', 'pro', 'scale']
    inboxes: Inboxes
    sends_today: SendsToday
    sending: Sending


class Day(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    received: int
    sent: int
    delivered: int
    bounced: int
    """
    Bounces and complaints
    """
    failed: int
    date: str
    """
    YYYY-MM-DD, UTC
    """


class Totals(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    received: int
    sent: int
    delivered: int
    bounced: int
    """
    Bounces and complaints
    """
    failed: int


class Stats(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['stats']
    from_: Annotated[AwareDatetime, Field(alias='from')]
    """
    Start of the first day (UTC)
    """
    days: list[Day]
    totals: Totals


class InboxList(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['list']
    data: list[Inbox]
    next_cursor: str | None


class MessageList(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['list']
    data: list[Message]
    next_cursor: str | None


class ThreadList(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['list']
    data: list[Thread]
    next_cursor: str | None


class ApiKeyList(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['list']
    data: list[ApiKey]
    next_cursor: str | None


class WebhookList(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['list']
    data: list[Webhook]
    next_cursor: str | None


class DeliveryList(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['list']
    data: list[Delivery]
    next_cursor: str | None


class DraftList(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    object: Literal['list']
    data: list[Draft]
    next_cursor: str | None
